"use client";

import { useState, useMemo } from "react";
import { FileCode2, Plus, Trash2, Copy, Check, Download } from "lucide-react";

// ── Types ─────────────────────────────────────────────────────────────────────

type VarType = "string" | "number" | "bool" | "list(string)" | "map(string)" | "any";

interface TfVar {
  name: string;
  type: VarType;
  value: string;
  sensitive: boolean;
}

// ── HCL generator ─────────────────────────────────────────────────────────────

function formatValue(type: VarType, raw: string): string {
  const v = raw.trim();
  if (type === "string") return `"${v}"`;
  if (type === "number" || type === "bool") return v || "0";
  if (type === "list(string)") {
    const items = v
      .split(",")
      .map((s) => s.trim())
      .filter(Boolean)
      .map((s) => `"${s}"`);
    return items.length ? `[${items.join(", ")}]` : `[]`;
  }
  if (type === "map(string)") {
    const pairs = v
      .split(",")
      .map((s) => s.trim())
      .filter(Boolean)
      .map((pair) => {
        const eqIdx = pair.indexOf("=");
        if (eqIdx === -1) return null;
        const k = pair.slice(0, eqIdx).trim();
        const val = pair.slice(eqIdx + 1).trim();
        return `  ${k} = "${val}"`;
      })
      .filter(Boolean);
    return pairs.length ? `{\n${pairs.join("\n")}\n}` : `{}`;
  }
  // any
  return v ? `"${v}"` : `""`;
}

function generateHCL(vars: TfVar[]): string {
  const header = `# Generated by DevsTool\n# https://devstool.vercel.app`;
  const lines: string[] = [header];

  for (const v of vars) {
    if (!v.name.trim()) continue;
    lines.push("");
    if (v.sensitive) lines.push("# sensitive");
    lines.push(`${v.name.trim()} = ${formatValue(v.type, v.value)}`);
  }

  return lines.join("\n");
}

// ── Default state ─────────────────────────────────────────────────────────────

const DEFAULT_VARS: TfVar[] = [
  { name: "region", type: "string", value: "us-east-1", sensitive: false },
  { name: "instance_count", type: "number", value: "2", sensitive: false },
  { name: "enable_monitoring", type: "bool", value: "true", sensitive: false },
];

// ── Reusable components ───────────────────────────────────────────────────────

const inputCls =
  "bg-zinc-950 border border-zinc-800 rounded-lg px-3 py-1.5 text-sm text-zinc-200 placeholder-zinc-600 focus:outline-none focus:border-zinc-600 transition-colors font-mono w-full";

const selectCls =
  "bg-zinc-950 border border-zinc-800 rounded-lg px-2 py-1.5 text-sm text-zinc-200 focus:outline-none focus:border-zinc-600 transition-colors w-full";

// ── Page ──────────────────────────────────────────────────────────────────────

export default function TerraformTfvarsPage() {
  const [vars, setVars] = useState<TfVar[]>(DEFAULT_VARS);
  const [copied, setCopied] = useState(false);

  const hcl = useMemo(() => generateHCL(vars), [vars]);

  const updateVar = (i: number, patch: Partial<TfVar>) => {
    setVars((prev) => {
      const next = [...prev];
      next[i] = { ...next[i], ...patch };
      return next;
    });
  };

  const addVar = () =>
    setVars((prev) => [
      ...prev,
      { name: "", type: "string", value: "", sensitive: false },
    ]);

  const removeVar = (i: number) =>
    setVars((prev) => prev.filter((_, idx) => idx !== i));

  const copy = () => {
    navigator.clipboard.writeText(hcl);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };

  const download = () => {
    const blob = new Blob([hcl], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "terraform.tfvars";
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex flex-col gap-4 h-full">
      {/* Header */}
      <div className="flex items-center justify-between flex-wrap gap-3 shrink-0">
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 rounded-lg bg-purple-500/10 border border-purple-500/20 flex items-center justify-center">
            <FileCode2 className="w-4 h-4 text-purple-400" />
          </div>
          <div>
            <h1 className="text-lg font-semibold text-white">
              Terraform tfvars Generator
            </h1>
            <p className="text-xs text-zinc-500">
              Define variables and generate a .tfvars file — all client-side
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={copy}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs bg-zinc-900 border border-zinc-800 rounded-lg text-zinc-400 hover:text-white transition-colors"
          >
            {copied ? (
              <Check className="w-3.5 h-3.5 text-emerald-400" />
            ) : (
              <Copy className="w-3.5 h-3.5" />
            )}
            {copied ? "Copied!" : "Copy"}
          </button>
          <button
            onClick={download}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs bg-purple-600 hover:bg-purple-500 rounded-lg text-white transition-colors"
          >
            <Download className="w-3.5 h-3.5" /> Download .tfvars
          </button>
        </div>
      </div>

      {/* Two-pane layout */}
      <div className="grid grid-cols-2 gap-4 flex-1 min-h-0">
        {/* Left: form */}
        <div className="bg-zinc-900 border border-zinc-800 rounded-xl p-4 overflow-y-auto no-scrollbar flex flex-col gap-4">
          <p className="text-xs text-zinc-500 uppercase tracking-wider font-medium">
            Variables
          </p>

          {/* Table header */}
          <div className="grid grid-cols-[1fr_120px_1fr_60px_32px] gap-2 items-center">
            <span className="text-xs text-zinc-500">Name</span>
            <span className="text-xs text-zinc-500">Type</span>
            <span className="text-xs text-zinc-500">Value</span>
            <span className="text-xs text-zinc-500 text-center">Sensitive</span>
            <span />
          </div>

          {/* Variable rows */}
          <div className="flex flex-col gap-2">
            {vars.map((v, i) => (
              <div
                key={i}
                className="grid grid-cols-[1fr_120px_1fr_60px_32px] gap-2 items-center"
              >
                {/* Name */}
                <input
                  type="text"
                  value={v.name}
                  maxLength={100}
                  onChange={(e) => updateVar(i, { name: e.target.value.slice(0, 100) })}
                  placeholder="variable_name"
                  spellCheck={false}
                  className={inputCls}
                />
                {/* Type */}
                <select
                  value={v.type}
                  onChange={(e) => updateVar(i, { type: e.target.value as VarType })}
                  className={selectCls}
                >
                  {(
                    [
                      "string",
                      "number",
                      "bool",
                      "list(string)",
                      "map(string)",
                      "any",
                    ] as VarType[]
                  ).map((t) => (
                    <option key={t} value={t}>
                      {t}
                    </option>
                  ))}
                </select>
                {/* Value */}
                <input
                  type="text"
                  value={v.value}
                  maxLength={500}
                  onChange={(e) => updateVar(i, { value: e.target.value.slice(0, 500) })}
                  placeholder={
                    v.type === "list(string)"
                      ? "a, b, c"
                      : v.type === "map(string)"
                      ? "k=v, k2=v2"
                      : "value"
                  }
                  spellCheck={false}
                  className={inputCls}
                />
                {/* Sensitive */}
                <div className="flex items-center justify-center">
                  <input
                    type="checkbox"
                    checked={v.sensitive}
                    onChange={(e) => updateVar(i, { sensitive: e.target.checked })}
                    className="w-4 h-4 rounded border-zinc-700 bg-zinc-900 accent-purple-500 cursor-pointer"
                  />
                </div>
                {/* Delete */}
                <button
                  onClick={() => removeVar(i)}
                  className="p-1 text-zinc-600 hover:text-red-400 transition-colors flex items-center justify-center"
                >
                  <Trash2 className="w-3.5 h-3.5" />
                </button>
              </div>
            ))}
          </div>

          {/* Add variable */}
          <button
            onClick={addVar}
            className="flex items-center gap-1.5 text-xs text-zinc-500 hover:text-zinc-300 transition-colors self-start mt-1"
          >
            <Plus className="w-3.5 h-3.5" /> Add Variable
          </button>

          {/* Type hints */}
          <div className="mt-auto pt-4 border-t border-zinc-800">
            <p className="text-xs text-zinc-600 leading-relaxed">
              <span className="text-zinc-500 font-medium">list(string)</span>{" "}
              — comma-separated values&nbsp;&nbsp;
              <span className="text-zinc-500 font-medium">map(string)</span>{" "}
              — key=value pairs, comma-separated
            </p>
          </div>
        </div>

        {/* Right: HCL output */}
        <div className="bg-zinc-900 border border-zinc-800 rounded-xl p-4 overflow-y-auto no-scrollbar">
          <p className="text-xs text-zinc-600 mb-3 uppercase tracking-wider font-medium">
            terraform.tfvars
          </p>
          <pre className="font-mono text-xs text-zinc-300 whitespace-pre leading-5">
            {hcl}
          </pre>
        </div>
      </div>
    </div>
  );
}
